### ISSUE TITLE
Map creation doesn't teleport you to a new location and set the Diamond block

### ISSUE THREAD

**Issue by Fritz-CO-KG** [toqix/InvasionMLG-Rush#18]

**Comment by toqix** [comment]
This happens due wrongly configured or saved maps were no coordinates are saved so the BuildManager doesn't know where to locate the new Map.

**Comment by Fritz-CO-KG** [comment]
So there may be some maps missing or what? Because after we built the map, the gameManager knew EXACTLY where to take us and the "edit map" mode also teleported us directly to the map

**Comment by Fritz-CO-KG** [comment]
Is this a configuration issue?

**Comment by toqix** [comment]
This is a configuration issue and this bug happens when no p1z coordinate can be loaded

**Comment by toqix** [comment]
This happenes because of sn older version of the buildmanager not setting a default p1z and if a builder didnt set it it never sets it to fix this you have to look for wrongly configured maps in the json and set the coordinates manually with newer version this shouldn't happen only if there's a loading error.

**Comment by Fritz-CO-KG** [comment]
So i should check the config and manually add all p1z coordinates?

**Comment by toqix** [comment]
Yes that's the only fix

**Comment by Fritz-CO-KG** [comment]
The other way such behaviour can occur is when there are maps "missing"...

**Comment by toqix** [comment]
created a check if the map and the coordinates can be loaded and if not aborts the edit or creation of the map
